# .github/workflows/main.yml
name: Python CI/CD for Calculator

# 1. ¿Cuándo se ejecuta este workflow?
on:
  push:
    branches: [ "main" ] # Cuando subes código a la rama 'main'
  pull_request:
    branches: [ "main" ] # Cuando abres una Pull Request a 'main'

# 2. Definición de los trabajos (jobs) a ejecutar
jobs:
  build-and-test:
    # El tipo de máquina donde se ejecutará (Ubuntu es el estándar)
    runs-on: ubuntu-latest

    # 3. Pasos que se ejecutarán en secuencia
    steps:
      # Paso 1: Descargar tu código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Puedes usar la versión que prefieras

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Revisar la calidad del código con el Linter (Ruff)
      # El pipeline fallará si encuentra errores de calidad.
      - name: Lint with Ruff
        run: |
          ruff check .

      # Paso 5: Correr las pruebas con Pytest
      # El pipeline fallará si alguna prueba no pasa.
      - name: Test with Pytest
        run: |
          pytest

      # --- Parte de Despliegue Continuo (CD) ---
      # Solo se ejecuta si los pasos anteriores fueron exitosos
      
      # Paso 6: Crear el ejecutable con PyInstaller
      - name: Build executable with PyInstaller
        # El "if" asegura que este paso solo corra en la rama 'main', no en Pull Requests
        if: github.ref == 'refs/heads/main'
        run: |
          pyinstaller --onefile --windowed --name="Calculadora" src/calculator_app.py

      # Paso 7: Subir el ejecutable como un "artefacto"
      # Esto te permitirá descargar el archivo desde la página de la acción en GitHub.
      - name: Upload executable artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-ejecutable-linux # Nombre del artefacto
          path: dist/Calculadora # Ruta donde PyInstaller crea el archivo